service: tbf-tasks
plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript

provider:
  name: aws
  region: us-west-2
  runtime: nodejs16.x

functions:
  market-catalog-indexer:
    handler: handlers/market-catalog-indexer.handler
    events:
      - http:
          method: GET
          path: /

# only include the Prisma binary required on AWS Lambda while packaging
package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
